name: badges

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync --extra test

      - name: Run tests
        run: uv run pytest

      - name: Generate coverage badge
        run: uv run python scripts/generate_coverage_badge.py

      - name: Generate python version badge
        run: uv run python scripts/generate_python_badge.py

      - name: Commit updated badge
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update badges'
          file_pattern: |
            coverage-badge.json
            python-badge.json
